name: Run Go Script
on: [push]
jobs:
  my-job:
    name: Run Go Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Install dependencies
        run: go mod init linear_algebra_competition && go get gonum.org/v1/gonum/...@latest
      - name: Run task one
        run: go build -o one go/one.go && ./one
      - name: Run task two
        run: go build -o two go/two.go && ./two
      - name: Run task three
        run: go build -o three go/three.go && ./three